name: sociobuzz_social_media_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # --- firebase ---
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.3

  flutter_bloc: ^8.1.6
  google_fonts: ^6.2.1
  file_picker: ^8.1.2
  cached_network_image: ^3.4.1
#  get: ^4.6.6



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  
#   assets:
#     - images/a_dot_burr.jpeg
#     - images/a_dot_ham.jpeg

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
